version: '3.8'
services:
  gitlab:
    image: gitlab/gitlab-ce:16.6.2-ce.0
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8888'
        nginx['listen_port'] = 8888
        gitlab_rails['initial_root_password'] = 'some_initial_password'
        gitlab_rails['gitlab_ssh_host'] = "localhost"
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        puma['worker_process'] = 0
      GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: some_registration_token
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/loga:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    ports:
      - '8888:8888'
      - '2222:22'
    healthcheck:
      test: curl --fail http://localhost:8888/users/sign_in || exit 1
      interval: 60s
      timeout: 3s
      retries: 10
  gitlab-runner:
    image: gitlab/gitlab-runner:ubuntu-v16.6.1
    container_name: gitlab-runner
    entrypoint: [""]
    command: ["/bin/sh", "-c", "gitlab-runner register \
                                --non-interactive \
                                --url 'hptt://localhost:8888' \
                                --token 'some_registration_token' \
                                --executor 'docker' \
                                --docker-network-mode 'host' \
                                --docker-image 'python:alpine' \
                                && gitlab-runner run --user=gitlab-runner --working-directory=/etc/gitlab-runner"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: 'host'
    depends_on:
      gitlab:
        condition: service_healthy
